// palavras.js
const palavras = [
  "abacaxi", "abelha", "abismo", "abstrato", "abundante", "acelera", "aceno", "acorde", "admirar", "adrenalina",
  "afeto", "aflicao", "agenda", "agil", "agitado", "alegria", "alface", "alga", "algodao", "alienigena",
  "alma", "altitude", "alvo", "amante", "amargo", "amendoim", "amigo", "amostra", "anagrama", "anao",
  "ancora", "andar", "anel", "anjo", "anomalia", "antecipar", "antidoto", "apito", "aplauso", "apogeu",
  "apostar", "aprender", "aproxima", "aquario", "arbitro", "arduo", "areia", "arvore", "asfalto", "aspirador",
  "astronauta", "atirador", "atitude", "atleta", "atmosfera", "atordoar", "atravessar", "atriz", "aumento", "aurora",
  "autentico", "aviador", "aviso", "azedo", "azul", "bacteria", "bailarina", "balanco", "balde", "bambu",
  "banheira", "banquete", "baralho", "barata", "barco", "barriga", "bateria", "bebe", "beijo", "beleza",
  "belo", "berco", "besouro", "bilhete", "bisavo", "bisnaga", "bloco", "boca", "bolacha", "bolha",
  "boliche", "bolo", "bomba", "bondade", "boneca", "borboleta", "bordado", "bosque", "branco", "bravura",
  "brilho", "brincadeira", "brinde", "broto", "bruxa", "bubonico", "burrito", "cabana", "cabelo", "cabide",
  "cabo", "cacau", "cachorro", "cadeira", "cafe", "caixa", "cajado", "calabresa", "calca", "calculo",
  "cama", "camelo", "caminhao", "campanha", "caneta", "canivete", "canto", "capacete", "capitao", "caracol",
  "caranguejo", "carinho", "carne", "carpinteiro", "carruagem", "cartao", "casa", "casaco", "casamento", "castelo",
  "cavalo", "cedro", "celeste", "cenoura", "cerca", "cerebro", "cimento", "cinema", "circulo", "circuito",
  "citar", "claridade", "classe", "classico", "coala", "cobertor", "cobra", "codigo", "colher", "colina",
  "comando", "cometa", "compaixao", "comunidade", "concerto", "concha", "concordar", "conduzir", "confianca", "congelar",
  "conhecimento", "conquista", "constelacao", "conta", "coragem", "coral", "corda", "corneta", "corpo", "corrida",
  "corte", "costela", "cotidiano", "cratera", "criatura", "cristal", "cronica", "cruzamento", "cubiculo", "curva",
  "dado", "dancar", "dedicacao", "dedo", "defesa", "degrau", "delicado", "demonstracao", "dentista", "depressao",
  "derrota", "desafio", "desenho", "deserto", "desfile", "desgraca", "despertador", "destino", "desvio", "diamante",
  "diario", "dinheiro", "dinossauro", "diploma", "disciplina", "disfarce", "distribuir", "divertido", "doce", "dominio",
  "dragao", "ducha", "educacao", "efeito", "elegante", "eleicao", "elefante", "elo", "embarcacao", "emocao",
  "empatia", "encontro", "energia", "enigma", "enlace", "enorme", "enredo", "ensinar", "entender", "entusiasmo",
  "envelope", "epopeia", "equilibrio", "erguer", "erro", "escada", "escama", "escapar", "esclarecer", "escorregar",
  "escravo", "esfera", "esforco", "esmalte", "espada", "espelho", "espeto", "esquilo", "estrela", "estrutura",
  "eternidade", "euforia", "evento", "exatamente", "excelencia", "excursao", "exercito", "exposicao", "faisca", "fala",
  "famoso", "fantasia", "farol", "fascinio", "fauna", "felicidade", "ferida", "feroz", "festa", "filme",
  "filtro", "fita", "flecha", "floresta", "flutuar", "fofoca", "fonte", "formiga", "fortaleza", "fosforo",
  "framboesa", "franqueza", "frasco", "freio", "frio", "fronteira", "fumaca", "furacao", "gaiola", "galaxia",
  "galho", "galo", "gama", "garantia", "garfo", "gargalhada", "gasolina", "gato", "gelo", "geleia",
  "gemeos", "gengibre", "gente", "gigante", "girassol", "golfinho", "gorro", "grao", "gratidão", "gravata",
  "grelha", "grilo", "grinalda", "grito", "guarda", "guaxinim", "guitarra", "habilidade", "helicoptero", "heranca",
  "heroi", "hino", "horizonte", "hortela", "humano", "humilde", "idolo", "ilha", "imagem", "imenso",
  "imitar", "impacto", "importante", "incrivel", "infinito", "informacao", "inimigo", "inovacao", "inseto", "inspiracao",
  "instante", "intenso", "interior", "interrogacao", "inverno", "invocar", "ironia", "isolamento", "jardim", "jasmim",
  "jato", "jazida", "jogo", "jornal", "jovem", "jubiloso", "juiz", "julgamento", "juncao", "juramento",
  "justica", "labirinto", "lago", "lama", "lanca", "lanche", "lapis", "laranja", "largura", "laser",
  "laco", "lavanda", "lealdade", "leao", "lebre", "leitura", "lembranca", "lentidao", "leque", "leveza",
  "liberdade", "lilas", "limite", "limonada", "linha", "linguagem", "lira", "livro", "lobisomem", "lobo",
  "lodo", "longevidade", "loucura", "lua", "luminaria", "macaco", "maca", "mafia", "magia", "magnata",
  "mala", "malha", "mama", "mangueira", "manha", "mar", "maravilha", "marmore", "marrom", "mascarar",
  "matematica", "medalha", "meditar", "melancia", "melodia", "memoria", "mentira", "mesa", "metal", "meteoro",
  "milagre", "mineral", "minusculo", "miragem", "moeda", "montanha", "mordida", "mosaico", "motivo", "mundo",
  "muralha", "musculoso", "musica", "nacional", "natureza", "navio", "nectar", "negocio", "neve", "ninho",
  "noite", "notavel", "novidade", "nuvem", "obedecer", "objeto", "obrigacao", "oceano", "oculto", "odor",
  "oficina", "oferta", "olhar", "onda", "opaco", "opala", "opinio", "oracao", "orgulho", "orientar",
  "ouvir", "oxigenio", "pacto", "palco", "palmirinha", "panela", "papel", "parabola", "paraiso", "pasta",
  "pato", "peca", "peixe", "pelo", "pencil", "pente", "pergunta", "perigo", "perfeito", "pequeno",
  "piano", "pico", "pilha", "pingente", "plano", "planta", "plutao", "polvo", "polvo", "porcao",
  "porta", "posta", "potencia", "praga", "praia", "presente", "producao", "quadro", "quasar", "quebra",
  "quadro", "quimico", "quintal", "rabisco", "radar", "raiz", "ralo", "ramo", "rapido", "reconhecer",
  "reflexo", "regra", "reinado", "relampago", "renovacao", "riso", "roda", "rolo", "rosa", "sabor",
  "salada", "salvar", "sangue", "sapo", "saudade", "sela", "semana", "sentido", "sereia", "sorriso",
  "sotaque", "sombrinha", "sonho", "sorrir", "sofrimento", "sofrer", "sorrir", "sol", "sonho", "superfice",
  "suspensao", "tabua", "taco", "tartaruga", "tatu", "teclado", "tempera", "templo", "tigre", "torre",
  "tradicao", "trevo", "tribo", "tropical", "turbulento", "urna", "urso", "utilidade", "vagalume", "valente",
  "vampiro", "variavel", "vassoura", "velocidade", "ventania", "vermelho", "verdade", "vespera", "vibracao", "vila",
  "vinho", "violao", "vivo", "voce", "voracidade", "vulcao", "xaxim", "zebra", "zelo"
];

module.exports = palavras;
