// palavras.js
const palavras = [
  "abacaxi", "abelha", "abismo", "abstrato", "abundante", "acelera", "aceno", "acorde", "admirar", "adrenalina",
  "afeto", "aflicao", "agenda", "agil", "agitado", "alegria", "alface", "alga", "algodao", "alienigena",
  "alma", "altitude", "alvo", "amante", "amargo", "amendoim", "amigo", "amostra", "anagrama", "anao",
  "ancora", "andar", "anel", "anjo", "anomalia", "antecipar", "antidoto", "apito", "aplauso", "apogeu",
  "apostar", "aprender", "aproxima", "aquario", "arbitro", "arduo", "areia", "arvore", "asfalto", "aspirador",
  "astronauta", "atirador", "atitude", "atleta", "atmosfera", "atordoar", "atravessar", "atriz", "aumento", "aurora",
  "autentico", "aviador", "aviso", "azedo", "azul", "bacteria", "bailarina", "balanco", "balde", "bambu",
  "banheira", "banquete", "baralho", "barata", "barco", "barriga", "bateria", "bebe", "beijo", "beleza",
  "belo", "berco", "besouro", "bilhete", "bisavo", "bisnaga", "bloco", "boca", "bolacha", "bolha",
  "boliche", "bolo", "bomba", "bondade", "boneca", "borboleta", "bordado", "bosque", "branco", "bravura",
  "brilho", "brincadeira", "brinde", "broto", "bruxa", "bubonico", "burrito", "cabana", "cabelo", "cabide",
  "cabo", "cacau", "cachorro", "cadeira", "cafe", "caixa", "cajado", "calabresa", "calca", "calculo",
  "cama", "camelo", "caminhao", "campanha", "caneta", "canivete", "canto", "capacete", "capitao", "caracol",
  "caranguejo", "carinho", "carne", "carpinteiro", "carruagem", "cartao", "casa", "casaco", "casamento", "castelo",
  "cavalo", "cedro", "celeste", "cenoura", "cerca", "cerebro", "cimento", "cinema", "circulo", "circuito",
  "citar", "claridade", "classe", "classico", "coala", "cobertor", "cobra", "codigo", "colher", "colina",
  "comando", "cometa", "compaixao", "comunidade", "concerto", "concha", "concordar", "conduzir", "confianca", "congelar",
  "conhecimento", "conquista", "constelacao", "conta", "coragem", "coral", "corda", "corneta", "corpo", "corrida",
  "corte", "costela", "cotidiano", "cratera", "criatura", "cristal", "cronica", "cruzamento", "cubiculo", "curva",
  "dado", "dancar", "dedicacao", "dedo", "defesa", "degrau", "delicado", "demonstracao", "dentista", "depressao",
  "derrota", "desafio", "desenho", "deserto", "desfile", "desgraca", "despertador", "destino", "desvio", "diamante",
  "diario", "dinheiro", "dinossauro", "diploma", "disciplina", "disfarce", "distribuir", "divertido", "doce", "dominio",
  "dragao", "ducha", "educacao", "efeito", "elegante", "eleicao", "elefante", "elo", "embarcacao", "emocao",
  "empatia", "encontro", "energia", "enigma", "enlace", "enorme", "enredo", "ensinar", "entender", "entusiasmo",
  "envelope", "epopeia", "equilibrio", "erguer", "erro", "escada", "escama", "escapar", "esclarecer", "escorregar",
  "escravo", "esfera", "esforco", "esmalte", "espada", "espelho", "espeto", "esquilo", "estrela", "estrutura",
  "eternidade", "euforia", "evento", "exatamente", "excelencia", "excursao", "exercito", "exposicao", "faisca", "fala",
  "famoso", "fantasia", "farol", "fascinio", "fauna", "felicidade", "ferida", "feroz", "festa", "filme",
  "filtro", "fita", "flecha", "floresta", "flutuar", "fofoca", "fonte", "formiga", "fortaleza", "fosforo",
  "framboesa", "franqueza", "frasco", "freio", "frio", "fronteira", "fumaca", "furacao", "gaiola", "galaxia",
  "galho", "galo", "gama", "garantia", "garfo", "gargalhada", "gasolina", "gato", "gelo", "geleia",
  "gemeos", "gengibre", "gente", "gigante", "girassol", "golfinho", "gorro", "grao", "gratidão", "gravata",
  "grelha", "grilo", "grinalda", "grito", "guarda", "guaxinim", "guitarra", "habilidade", "helicoptero", "heranca",
  "heroi", "hino", "horizonte", "hortela", "humano", "humilde", "idolo", "ilha", "imagem", "imenso",
  "imitar", "impacto", "importante", "incrivel", "infinito", "informacao", "inimigo", "inovacao", "inseto", "inspiracao",
  "instante", "intenso", "interior", "interrogacao", "inverno", "invocar", "ironia", "isolamento", "jardim", "jasmim",
  "jato", "jazida", "jogo", "jornal", "jovem", "jubiloso", "juiz", "julgamento", "juncao", "juramento",
  "justica", "labirinto", "lago", "lama", "lanca", "lanche", "lapis", "laranja", "largura", "laser",
  "laco", "lavanda", "lealdade", "leao", "lebre", "leitura", "lembranca", "lentidao", "leque", "leveza",
  "liberdade", "lilas", "limite", "limonada", "linha", "linguagem", "lira", "livro", "lobisomem", "lobo",
  "lodo", "longevidade", "loucura", "lua", "luminaria", "macaco", "maca", "mafia", "magia", "magnata",
  "mala", "malha", "mama", "mangueira", "manha", "mar", "maravilha", "marmore", "marrom", "mascarar",
  "matematica", "medalha", "meditar", "melancia", "melodia", "memoria", "mentira", "mesa", "metal", "meteoro",
  "milagre", "mineral", "minusculo", "miragem", "moeda", "montanha", "mordida", "mosaico", "motivo", "mundo",
  "muralha", "musculoso", "musica", "nacional", "natureza", "navio", "nectar", "negocio", "neve", "ninho",
  "noite", "notavel", "novidade", "nuvem", "obedecer", "objeto", "obrigacao", "oceano", "oculto", "odor",
  "oferta", "olhar", "ombro", "onda", "opcao", "operador", "oponente", "oracao", "ordem", "organico",
  "origem", "ornamento", "ouro", "ousadia", "paciente", "pacote", "padaria", "padrinho", "pagar", "pajaro",
  "palavra", "palhaco", "palito", "pancada", "pandemia", "panela", "pantano", "pao", "papagaio", "papel",
  "paraiso", "parede", "partida", "passagem", "passo", "pastel", "patada", "patria", "peculiar", "pedra",
  "pegar", "peixe", "pele", "pente", "perceber", "perda", "perfeicao", "perigo", "perna", "perola",
  "pescador", "piano", "picante", "pijama", "piloto", "pimenta", "pincel", "pino", "pirata", "placa",
  "planeta", "planta", "plasma", "praia", "prato", "prazer", "precioso", "predio", "preguica", "premio",
  "presente", "pressao", "preto", "primitivo", "princesa", "prisioneiro", "privilegio", "problema", "processo", "profundo",
  "projeto", "promessa", "proposito", "protecao", "prova", "prumo", "pudim", "pulso", "pureza", "quadro",
  "queda", "quente", "quimera", "quisito", "rabisco", "raio", "raiz", "ramo", "rapido", "raposa",
  "raquete", "raro", "rascunho", "rasgado", "realeza", "rebeldia", "recompensa", "recriar", "reflexo", "refrigerante",
  "regiao", "relacao", "relampago", "relogio", "relva", "remedio", "resgate", "resistencia", "respeito", "restaurante",
  "retangulo", "retorno", "revelacao", "reverencia", "revista", "rigido", "riqueza", "ritmo", "robusto", "rocha",
  "rodeio", "rosa", "roteiro", "rotina", "sabor", "sabedoria", "sabre", "sacerdote", "saco", "sagaz",
  "sala", "salto", "salvador", "samba", "sanduiche", "sangue", "sapo", "saturno", "saudade", "segredo",
  "selva", "semente", "sensacao", "sentido", "serenidade", "serpente", "silencio", "simplicidade", "sinfonia", "sino",
  "sistema", "sobrenatural", "socio", "soldado", "solidao", "sombrinha", "sonho", "sorriso", "sorte", "suavidade",
  "sucesso", "sufoco", "sumo", "superacao", "surpresa", "susto", "tabela", "tabuleta", "taco", "talento",
  "talvez", "tampa", "tangente", "tartaruga", "tempestade", "templo", "tenacidade", "tenda", "tendencia", "tenso",
  "teoria", "terapia", "terno", "tesouro", "textura", "tigre", "tijolo", "timidez", "tiro", "tocha",
  "tolerancia", "tomate", "tormenta", "torneio", "tornado", "tortura", "tradicao", "traje", "trampo", "transparencia",
  "trapaceiro", "travo", "treinamento", "trevo", "tribo", "tristeza", "triunfo", "trofeu", "trompete", "truque",
  "tulipa", "turista", "turquesa", "uivo", "ultraje", "uniao", "universo", "urso", "utilidade", "uva",
  "valente", "vapor", "variavel", "veiculo", "velocidade", "ventania", "verao", "verdade", "vergonha", "verniz",
  "verossimil", "versao", "vertigem", "vestigio", "vetor", "viajante", "vida", "vidro", "vigia", "vila",
  "vinho", "violino", "virtude", "visao", "vitamina", "vitoria", "vivo", "voador", "voluntario", "vontade",
  "voo", "vulcao", "xale", "xicara", "zarpar"
];

  
  export default palavras;
  