// palavras.js
const palavras = [
    "abacaxi", "abelha", "abismo", "abstrato", "abundante", "acelera", "aceno", "acorde", "admirar", "adrenalina",
    "afeto", "aflição", "agenda", "ágil", "agitado", "alegria", "alface", "alga", "algodão", "alienígena",
    "alma", "altitude", "alvo", "amante", "amargo", "amendoim", "amigo", "amostra", "anagrama", "anão",
    "âncora", "andar", "anel", "anjo", "anomalia", "antecipar", "antídoto", "apito", "aplauso", "apogeu",
    "apostar", "aprender", "aproxima", "aquário", "árbitro", "árduo", "areia", "árvore", "asfalto", "aspirador",
    "astronauta", "atirador", "atitude", "atleta", "atmosfera", "atordoar", "atravessar", "atriz", "aumento", "aurora",
    "autêntico", "aviador", "aviso", "azedo", "azul", "bactéria", "bailarina", "balanço", "balde", "bambu",
    "banheira", "banquete", "baralho", "barata", "barco", "barriga", "bateria", "bebê", "beijo", "beleza",
    "belo", "berço", "besouro", "bilhete", "bisavô", "bisnaga", "bloco", "boca", "bolacha", "bolha",
    "boliche", "bolo", "bomba", "bondade", "boneca", "borboleta", "bordado", "bosque", "branco", "bravura",
    "brilho", "brincadeira", "brinde", "broto", "bruxa", "bubônica", "burrito", "cabana", "cabelo", "cabide",
    "cabo", "cacau", "cachorro", "cadeira", "café", "caixa", "cajado", "calabresa", "calça", "cálculo",
    "cama", "camelo", "caminhão", "campanha", "caneta", "canivete", "canto", "capacete", "capitão", "caracol",
    "caranguejo", "carinho", "carne", "carpinteiro", "carruagem", "cartão", "casa", "casaco", "casamento", "castelo",
    "cavalo", "cedro", "celeste", "cenoura", "cerca", "cérebro", "cimento", "cinema", "círculo", "circuito",
    "citar", "claridade", "classe", "clássico", "coala", "cobertor", "cobra", "código", "colher", "colina",
    "comando", "cometa", "compaixão", "comunidade", "concerto", "concha", "concordar", "conduzir", "confiança", "congelar",
    "conhecimento", "conquista", "constelação", "conta", "coragem", "coral", "corda", "corneta", "corpo", "corrida",
    "corte", "costela", "cotidiano", "cratera", "criatura", "cristal", "crônica", "cruzamento", "cubículo", "curva",
    "dado", "dançar", "dedicação", "dedo", "defesa", "degrau", "delicado", "demonstração", "dentista", "depressão",
    "derrota", "desafio", "desenho", "deserto", "desfile", "desgraça", "despertador", "destino", "desvio", "diamante",
    "diário", "dinheiro", "dinossauro", "diploma", "disciplina", "disfarce", "distribuir", "divertido", "doce", "domínio",
    "dragão", "ducha", "educação", "efeito", "elegante", "eleição", "elefante", "elo", "embarcação", "emoção",
    "empatia", "encontro", "energia", "enigma", "enlace", "enorme", "enredo", "ensinar", "entender", "entusiasmo",
    "envelope", "epopeia", "equilíbrio", "erguer", "erro", "escada", "escama", "escapar", "esclarecer", "escorregar",
    "escravo", "esfera", "esforço", "esmalte", "espada", "espelho", "espeto", "esquilo", "estrela", "estrutura",
    "eternidade", "euforia", "evento", "exatamente", "excelência", "excursão", "exército", "exposição", "faísca", "fala",
    "famoso", "fantasia", "farol", "fascínio", "fauna", "felicidade", "ferida", "feroz", "festa", "filme",
    "filtro", "fita", "flecha", "floresta", "flutuar", "fofoca", "fonte", "formiga", "fortaleza", "fósforo",
    "framboesa", "franqueza", "frasco", "freio", "frio", "fronteira", "fumaça", "furacão", "gaiola", "galáxia",
    "galho", "galo", "gama", "garantia", "garfo", "gargalhada", "gasolina", "gato", "gelo", "geleia",
    "gêmeos", "gengibre", "gente", "gigante", "girassol", "golfinho", "gorro", "grão", "gratidão", "gravata",
    "grelha", "grilo", "grinalda", "grito", "guarda", "guaxinim", "guitarra", "habilidade", "helicóptero", "herança",
    "herói", "hino", "horizonte", "hortelã", "humano", "humilde", "ídolo", "ilha", "imagem", "imenso",
    "imitar", "impacto", "importante", "incrível", "infinito", "informação", "inimigo", "inovação", "inseto", "inspiração",
    "instante", "intenso", "interior", "interrogação", "inverno", "invocar", "ironia", "isolamento", "jardim", "jasmim",
    "jato", "jazida", "jogo", "jornal", "jovem", "jubiloso", "juiz", "julgamento", "junção", "juramento",
    "justiça", "labirinto", "lago", "lama", "lança", "lanche", "lápis", "laranja", "largura", "laser",
    "laço", "lavanda", "lealdade", "leão", "lebre", "leitura", "lembrança", "lentidão", "leque", "leveza",
    "liberdade", "lilás", "limite", "limonada", "linha", "linguagem", "lira", "livro", "lobisomem", "lobo",
    "lodo", "longevidade", "loucura", "lua", "luminária", "macaco", "maçã", "máfia", "magia", "magnata",
    "mala", "malha", "mama", "mangueira", "manhã", "mar", "maravilha", "mármore", "marrom", "mascarar",
    "matemática", "medalha", "meditar", "melancia", "melodia", "memória", "mentira", "mesa", "metal", "meteoro",
    "milagre", "mineral", "minúsculo", "miragem", "moeda", "montanha", "mordida", "mosaico", "motivo", "mundo",
    "muralha", "musculoso", "música", "nacional", "natureza", "navio", "néctar", "negócio", "neve", "ninho",
    "noite", "notável", "novidade", "nuvem", "obedecer", "objeto", "obrigação", "oceano", "oculto", "odor",
    "oferta", "olhar", "ombro", "onda", "onírico", "opção", "oráculo", "órbita", "orquestra", "ouro",
    "ovo", "pacto", "pagamento", "página", "pálido", "pântano", "papel", "parada", "parceria", "paredes",
    "pássaro", "passo", "pastel", "patamar", "pato", "patrimônio", "pausa", "peça", "pedra", "peixe",
    "pele", "pelo", "pena", "pente", "percurso", "perda", "perfeição", "perfil", "pergaminho", "perigo",
    "permanecer", "perspectiva", "pesadelo", "pesquisa", "pés", "petróleo", "piano", "pico", "pimenta", "pinça",
    "pintor", "pipoca", "pirata", "pista", "planeta", "plano", "plástico", "platina", "pluma", "poço",
    "poesia", "ponto", "porção", "portão", "posse", "possível", "posta", "prancha", "prazer", "precipício",
    "preguiça", "prelúdio", "preparação", "pressa", "pressentimento", "primavera", "princípio", "privacidade", "problema", "procurar",
    "profundo", "progresso", "projeto", "promessa", "protetor", "prova", "publicar", "pulso", "punhado", "pura", "cebolar"
  ];
  
  export default palavras;
  